# Generated by Django 2.0.7 on 2018-09-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0003_auto_20180913_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
