# Generated by Django 2.1.1 on 2018-09-15 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0007_auto_20180915_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
