# Generated by Django 2.1.1 on 2018-09-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0009_auto_20180915_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='desired_skills',
        ),
        migrations.RemoveField(
            model_name='form',
            name='job',
        ),
    ]
